--- #YAML:1.0
name:               Weather-TW
version:            0.32
abstract:           Fetch Taiwan weather data from L<http://www.cwb.gov.tw/>
author:
    - dryman <idryman@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    HTML::Element:      0
    HTML::TreeBuilder:  0
    JSON:               0
    LWP::UserAgent:     0
    XML::Smart:         0
    YAML:               0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
