---
abstract: 'Fetch Taiwan weather data from L<http://www.cwb.gov.tw/>'
author:
  - 'dryman, <idryman@gmail.com>'
  - 'dryman <idryman@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0
  Test::More::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Weather-TW
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DateTime: 0.7
  HTML::Element: 0
  HTML::TreeBuilder: 0
  JSON: 0
  LWP::Simple: 6
  LWP::UserAgent: 0
  Moose: 2.04
  XML::Smart: 0
  YAML: 0
  perl: 5.8.6
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.500002
